// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package caddy_oidc

import (
	"errors"
	"fmt"
)

const (
	// ActionAllow is a Action of type Allow.
	ActionAllow Action = iota
	// ActionDeny is a Action of type Deny.
	ActionDeny
)

var ErrInvalidAction = errors.New("not a valid Action")

const _ActionName = "allowdeny"

var _ActionMap = map[Action]string{
	ActionAllow: _ActionName[0:5],
	ActionDeny:  _ActionName[5:9],
}

// String implements the Stringer interface.
func (x Action) String() string {
	if str, ok := _ActionMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Action(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Action) IsValid() bool {
	_, ok := _ActionMap[x]
	return ok
}

var _ActionValue = map[string]Action{
	_ActionName[0:5]: ActionAllow,
	_ActionName[5:9]: ActionDeny,
}

// ParseAction attempts to convert a string to a Action.
func ParseAction(name string) (Action, error) {
	if x, ok := _ActionValue[name]; ok {
		return x, nil
	}
	return Action(0), fmt.Errorf("%s is %w", name, ErrInvalidAction)
}

// MarshalText implements the text marshaller method.
func (x Action) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Action) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseAction(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Action) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// EvaluationResultImplicitDeny is a EvaluationResult of type Implicit Deny.
	EvaluationResultImplicitDeny EvaluationResult = iota
	// EvaluationResultExplicitDeny is a EvaluationResult of type Explicit Deny.
	EvaluationResultExplicitDeny
	// EvaluationResultAllow is a EvaluationResult of type Allow.
	EvaluationResultAllow
)

var ErrInvalidEvaluationResult = errors.New("not a valid EvaluationResult")

const _EvaluationResultName = "implicit denyexplicit denyallow"

var _EvaluationResultMap = map[EvaluationResult]string{
	EvaluationResultImplicitDeny: _EvaluationResultName[0:13],
	EvaluationResultExplicitDeny: _EvaluationResultName[13:26],
	EvaluationResultAllow:        _EvaluationResultName[26:31],
}

// String implements the Stringer interface.
func (x EvaluationResult) String() string {
	if str, ok := _EvaluationResultMap[x]; ok {
		return str
	}
	return fmt.Sprintf("EvaluationResult(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x EvaluationResult) IsValid() bool {
	_, ok := _EvaluationResultMap[x]
	return ok
}

var _EvaluationResultValue = map[string]EvaluationResult{
	_EvaluationResultName[0:13]:  EvaluationResultImplicitDeny,
	_EvaluationResultName[13:26]: EvaluationResultExplicitDeny,
	_EvaluationResultName[26:31]: EvaluationResultAllow,
}

// ParseEvaluationResult attempts to convert a string to a EvaluationResult.
func ParseEvaluationResult(name string) (EvaluationResult, error) {
	if x, ok := _EvaluationResultValue[name]; ok {
		return x, nil
	}
	return EvaluationResult(0), fmt.Errorf("%s is %w", name, ErrInvalidEvaluationResult)
}

// MarshalText implements the text marshaller method.
func (x EvaluationResult) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *EvaluationResult) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseEvaluationResult(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *EvaluationResult) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
