// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package authenticator

import (
	"errors"
	"fmt"
)

const (
	// AuthMethodNone is a AuthMethod of type none.
	AuthMethodNone AuthMethod = "none"
	// AuthMethodBearer is a AuthMethod of type bearer.
	AuthMethodBearer AuthMethod = "bearer"
	// AuthMethodCookie is a AuthMethod of type cookie.
	AuthMethodCookie AuthMethod = "cookie"
)

var ErrInvalidAuthMethod = errors.New("not a valid AuthMethod")

// String implements the Stringer interface.
func (x AuthMethod) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x AuthMethod) IsValid() bool {
	_, err := ParseAuthMethod(string(x))
	return err == nil
}

var _AuthMethodValue = map[string]AuthMethod{
	"none":   AuthMethodNone,
	"bearer": AuthMethodBearer,
	"cookie": AuthMethodCookie,
}

// ParseAuthMethod attempts to convert a string to a AuthMethod.
func ParseAuthMethod(name string) (AuthMethod, error) {
	if x, ok := _AuthMethodValue[name]; ok {
		return x, nil
	}
	return AuthMethod(""), fmt.Errorf("%s is %w", name, ErrInvalidAuthMethod)
}

// MarshalText implements the text marshaller method.
func (x AuthMethod) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *AuthMethod) UnmarshalText(text []byte) error {
	tmp, err := ParseAuthMethod(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *AuthMethod) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
