// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package authenticator

import (
	"errors"
	"fmt"
)

const (
	// SameSiteLax is a SameSite of type lax.
	SameSiteLax SameSite = "lax"
	// SameSiteStrict is a SameSite of type strict.
	SameSiteStrict SameSite = "strict"
	// SameSiteNone is a SameSite of type none.
	SameSiteNone SameSite = "none"
)

var ErrInvalidSameSite = errors.New("not a valid SameSite")

// String implements the Stringer interface.
func (x SameSite) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x SameSite) IsValid() bool {
	_, err := ParseSameSite(string(x))
	return err == nil
}

var _SameSiteValue = map[string]SameSite{
	"lax":    SameSiteLax,
	"strict": SameSiteStrict,
	"none":   SameSiteNone,
}

// ParseSameSite attempts to convert a string to a SameSite.
func ParseSameSite(name string) (SameSite, error) {
	if x, ok := _SameSiteValue[name]; ok {
		return x, nil
	}
	return SameSite(""), fmt.Errorf("%s is %w", name, ErrInvalidSameSite)
}

// MarshalText implements the text marshaller method.
func (x SameSite) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *SameSite) UnmarshalText(text []byte) error {
	tmp, err := ParseSameSite(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *SameSite) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
